# Generated by Django 4.2.11 on 2024-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarant',
            name='username',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='declarant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
